export const AuthActionType = {
  GET_LOGGED_IN: "GET_LOGGED_IN",
  LOGIN_USER: "LOGIN_USER",
  LOGOUT_USER: "LOGOUT_USER",
  REGISTER_USER: "REGISTER_USER",
  CHANGE_USERNAME: "CHANGE_USERNAME",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",
  SET_CURRENT_MODAL: "SET_CURRENT_MODAL",
  GUEST_USER: "GUEST_USER"
};