export const CurrentModal = {
  NONE: "NONE",
  DELETE_MAP: "DELETE_MAP",
  PUBLISH_MAP: "PUBLISH_MAP",
  SHARE_MAP: "SHARE_MAP",
  EXPORT_MAP: "EXPORT_MAP",
  ACCOUNT_FEEDBACK: "ACCOUNT_FEEDBACK",
  CHANGE_USERNAME: "CHANGE_USERNAME",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",
  CREATE_MAP: "CREATE_MAP",
  TAG: "TAG",
  FORGOT_PASSWORD: "FORGOT_PASSWORD",
};