export const EditMode = {
  NONE: "NONE",
  VIEW: "VIEW",
  EDIT_VERTEX: "EDIT_VERTEX",
  ADD_VERTEX: "ADD_VERTEX",
  MOVE_VERTEX: "MOVE_VERTEX",
  REMOVE_VERTEX: "REMOVE_VERTEX",
  SPLIT_SUBREGION: "SPLIT_SUBREGION",
  MERGE_SUBREGION: "MERGE_SUBREGION",
  ADD_SUBREGION: "ADD_SUBREGION",
  REMOVE_SUBREGION: "REMOVE_SUBREGION",
  UNDO: "UNDO",
  REDO: "REDO",
  ADD_OR_SPLIT_SUBREGION: "ADD_OR_SPLIT_SUBREGION",
  EDIT_TOOLBAR: "EDIT_TOOLBAR",
  UNDO_REDO: "UNDO_REDO",
  MERGING: "MERGING",
  MERGE_READY: "MERGE_READY"
}