export const EditMode = {
  NONE: "NONE",
  VIEW: "VIEW",
  ADD_VERTEX: "ADD_VERTEX",
  EDIT_VERTEX: "EDIT_VERTEX",
  SPLIT_SUBREGION: "SPLIT_SUBREGION",
  MERGE_SUBREGION: "MERGE_SUBREGION",
  ADD_SUBREGION: "ADD_SUBREGION",
  REMOVE_SUBREGION: "REMOVE_SUBREGION"
}