export const GlobalFileActionType = {
  SET_EDIT_MODE: "SET_EDIT_MODE",
  SET_EDIT_MODE_OPTION: "SET_EDIT_MODE_OPTION",
  SET_EDIT_MODE_ACTION: "SET_EDIT_MODE_ACTION",
  SET_UNDO_REDO_ACCESS: "SET_UNDO_REDO_ACCESS",
  RESET_DEFAULT: "RESET_DEFAULT"
}