export const GlobalFileActionType = {
  LOAD_SUBREGIONS: "LOAD_SUBREGIONS",
  UPDATE_VERTICE: "UPDATE_VERTICE",
  UPDATE_SUBREGION: "UPDATE_SUBREGION",
  UPDATE_PROJECT_TITLE: "UPDATE_PROJECT_TITLE",
  UPDATE_TAG: "UPDATE_TAG",
  UPDATE_COLLABORATOR: "UPDATE_COLLABORATOR",
  CHANGE_MODE: "CHANGE_MODE",
  UNDO: "UNDO",
  REDO: "REDO"
}