export const GlobalStoreActionType = {
  SET_VIEW_MODE: "SET_VIEW_MODE",
  SET_SELECTED_MAP: "SET_SELECTED_MAP",
  SET_DETAIL_VIEW: "SET_DETAIL_VIEW",
  SET_CURRENT_MODAL: "SET_CURRENT_MODAL",
  SET_OPENED_MAP: "SET_OPENED_MAP",
  LOAD_PERSONAL_AND_SHARED_MAPS: "LOAD_PERSONAL_AND_SHARED_MAPS",
  LOAD_ALL_MAPS: "LOAD_ALL_MAPS",
  PUBLISH_MAP: "PUBLISH_MAP",
};