export const GlobalFileActionType = {
  LOAD_SUBREGIONS: "LOAD_SUBREGIONS",
  UPDATE_SUBREGIONS: "UPDATE_SUBREGIONS",
  UPDATE_VERTICE: "UPDATE_VERTICE",
  UPDATE_PROJECT_TITLE: "UPDATE_PROJECT_TITLE",
  UPDATE_TAG: "UPDATE_TAG",
  UPDATE_COLLABORATOR: "UPDATE_COLLABORATOR",
  CHANGE_MODE: "CHANGE_MODE",
  UNDO: "UNDO",
  REDO: "REDO",
  SET_EDIT_MODE: "SET_EDIT_MODE",
  UPDATE_EDIT_REGIONS: "UPDATE_EDIT_REGIONS",
  SET_VERSION: "SET_VERSION",
  INCREMENT_VERSION_AND_UPDATE_SUBREGIONS: "INCREMENT_VERSION_AND_UPDATE_SUBREGIONS",
  REFRESH: "REFRESH",
  SET_EDIT_MODE_OPTION: "SET_EDIT_MODE_OPTION",
  RESET_DEFAULT: "RESET_DEFAULT"
}