name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies for Server
        run: npm ci
        working-directory: ./server
      
      - name: Install Dependencies for Client
        run: npm ci
        working-directory: ./client

      - name: Create server .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_ENVIRONMENT: DEVELOPMENT
          envkey_DB_CONNECT: ${{ secrets.DB_CONNECT }}
          envkey_DEV_CORS: ${{ vars.DEV_CORS }}
          envkey_PROD_CORS: ${{ secrets.PROD_CORS }}
          envkey_JWT_SECRET: ${{ secrets.JWT_SECRET }}
          envkey_SMTP_EMAIL: ${{ secrets.SMTP_EMAIL }}
          envkey_SMTP_KEY: ${{ secrets.SMTP_KEY }}
          envkey_SMTP_SENDEMAIL: ${{ secrets.SMTP_SENDEMAIL }}
          file_name: ./server/.env
          fail_on_empty: true     

      - name: Create client .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_REACT_APP_AUTH: '${{ vars.REACT_APP_AUTH }}'
          envkey_REACT_APP_STORE: "${{ vars.REACT_APP_STORE }}"
          envkey_REACT_APP_FILE: "${{ vars.REACT_APP_FILE }}"
          file_name: ./client/.env.development
          fail_on_empty: true
      
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v5.6.1 # use the explicit version number
        with:
          working-directory: ./tests/client_tests
          start: npm run start-client, npm run start-server
          wait-on: '${{ vars.DEV_CORS }}'