name: Backend Tests

on:
  push:
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies for Server Tests
        run: npm install
        working-directory: ./tests/server_tests
        
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DEBUG: false
          envkey_DB_CONNECT: ${{ secrets.DB_CONNECT }}
          file_name: ./tests/server_tests/.env
          fail_on_empty: true
        
      - name: Run Tests
        run: npm test
        working-directory: ./tests/server_tests