name: Backend Tests

on:
  push:
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies for Server
        run: npm ci
        working-directory: ./server

      - name: Install Dependencies for Server Tests
        run: npm ci
        working-directory: ./tests/server_tests

      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_ENVIRONMENT: PRODUCTION
          envkey_DB_CONNECT: ${{ secrets.DB_CONNECT }}
          envkey_DEV_CORS: ${{ vars.DEV_CORS }}
          envkey_PROD_CORS: ${{ secrets.PROD_CORS }}
          envkey_JWT_SCRET: ${{ secrets.JWT_SECRET }}
          file_name: ./server/.env
          fail_on_empty: true
        
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DEBUG: false
          envkey_DB_CONNECT: ${{ secrets.DB_CONNECT }}
          envkey_JWT_SECRET: ${{ secrets.JWT_SECRET }}
          envkey_SMTP_EMAIL: ${{ secrets.SMTP_EMAIL }}
          envkey_SMTP_KEY: ${{ secrets.SMTP_KEY }}
          envkey_SMTP_SENDEMAIL: ${{ secrets.SMTP_SENDEMAIL }}
          file_name: ./tests/server_tests/.env
          fail_on_empty: true
        
      - name: Run Tests
        run: npm test
        working-directory: ./tests/server_tests