name: CI/CD SERVER

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - uses: actions/checkout@v2

      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_ENVIRONMENT: PRODUCTION
          envkey_DB_CONNECT: ${{ secrets.DB_CONNECT }}
          envkey_DEV_CORS: ${{ vars.DEV_CORS }}
          envkey_PROD_CORS: ${{ secrets.PROD_CORS }}
          envkey_JWT_SECRET: ${{ secrets.JWT_SECRET }}
          envkey_SMTP_EMAIL: ${{ secrets.SMTP_EMAIL }}
          envkey_SMTP_KEY: ${{ secrets.SMTP_KEY }}
          envkey_SMTP_SENDEMAIL: ${{ secrets.SMTP_SENDEMAIL }}
          file_name: ./server/.env
          fail_on_empty: true

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./server/
          remote_path: /home/ubuntu/MapStory/server/
          remote_host:  ${{ secrets.REMOTE_HOST }}
          remote_user: ubuntu
          remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"
      